# Vector

Import NumPy.

In [1]:
import numpy as np

Generate vector appropriately

In [2]:
x = np.array([5,-2]) # assign the vector [5, -2] to x
x

array([ 5, -2])

Get vector information

In [3]:
x.ndim  # Array dimension

1

In [4]:
x.shape # Array size (dimension of vector)

(2,)

In [5]:
len(x)  # Number of elements of array

2

Another way to generate a vector.

In [6]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
b = np.arange(0, 5)
b

array([0, 1, 2, 3, 4])

In [8]:
c = np.arange(10, 2, -2)
c

array([10,  8,  6,  4])

In [9]:
d = np.arange(10, 2, -2)
d

array([10,  8,  6,  4])