# Vector

Import NumPy.

In [1]:
import numpy as np

Generate vector appropriately

In [2]:
x = np.array([5,-2]) # assign the vector(i.e 1-D array) [5, -2] to x
x

array([ 5, -2])

Get vector information

In [3]:
x.ndim  # Array dimension

1

In [4]:
x.shape # Array size (dimension of vector)

(2,)

In [5]:
len(x)  # Number of elements of array

2

Another way to generate a vector.

In [6]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
b = np.arange(0, 5)
b

array([0, 1, 2, 3, 4])

In [8]:
c = np.arange(10, 2, -2)
c

array([10,  8,  6,  4])

In [9]:
d = np.arange(10, -3, -2.5)
d

array([10. ,  7.5,  5. ,  2.5,  0. , -2.5])

In [10]:
d[3]

2.5

In [11]:
d[0:3]

array([10. ,  7.5,  5. ])

In [12]:
d[:3]; d[3:]

array([ 2.5,  0. , -2.5])

In [13]:
d > 2

array([ True,  True,  True,  True, False, False])

In [14]:
d[d > 0]

array([10. ,  7.5,  5. ,  2.5])

# Matrix

In [15]:
A = np.array([[1, 2], [3, 4]]); 
B = np.array([[-5, -6], [-7, -8]])

In [16]:
A

array([[1, 2],
       [3, 4]])

In [17]:
B

array([[-5, -6],
       [-7, -8]])

In [18]:
np.r_[A, B] # 行列を縦方向に並べる

array([[ 1,  2],
       [ 3,  4],
       [-5, -6],
       [-7, -8]])

In [19]:
C = np.c_[A, B] # 行列を横方向に並べる
C

array([[ 1,  2, -5, -6],
       [ 3,  4, -7, -8]])

In [20]:
A.shape # Aのサイズ

(2, 2)

In [21]:
C.shape # Cのサイズ

(2, 4)

In [22]:
C.T # 転置

array([[ 1,  3],
       [ 2,  4],
       [-5, -7],
       [-6, -8]])

In [23]:
E = np.arange(1, 9).reshape(2, 4) # ベクトルを 2x4 行列に変形
E

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
E[0, 0]  # (0,1)成分

1

In [25]:
E[1, 2]  # (1,2)成分 

7

In [26]:
E[:, 1] # 第1列

array([2, 6])

In [27]:
E[0:, 2:] # 第0行以降 かつ 第2列以降

array([[3, 4],
       [7, 8]])

In [28]:
E[:, [0, 1]] # 第0,1列

array([[1, 2],
       [5, 6]])

In [29]:
E[:, ::-1] # 列を逆順にする

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [30]:
E[::-1, ::-1] # 列・行ともに逆順にする

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [31]:
np.delete(E,1,1)   # Aの1列を削除(axis=1)

array([[1, 3, 4],
       [5, 7, 8]])

In [32]:
np.delete(E,[1,2],1)     # Aの1，2列を削除

array([[1, 4],
       [5, 8]])

In [33]:
np.delete(A,[0,0],0)     # Aの0，2行を削除(axis=0)

array([[3, 4]])

In [34]:
F = np.arange(1, 17)
F

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [35]:
G = F.reshape(4, 4)
G

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
np.diag(G)              # 対角成分

array([ 1,  6, 11, 16])

In [37]:
np.fill_diagonal(G, G.diagonal()+10)  # Bの対角成分に 10を加える
G

array([[11,  2,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 10, 21, 12],
       [13, 14, 15, 26]])

In [38]:
e = np.array([1,2,-1, 3])         # ベクトル d を作成
z = np.linalg.solve(G,e)       # Bz=d を解く
z

array([ 0.07888889,  0.13      , -0.21888889,  0.13222222])

In [39]:
np.dot(np.linalg.inv(G),e)     # B の逆行列と d の積．z と一致

array([ 0.07888889,  0.13      , -0.21888889,  0.13222222])

In [40]:
eigen = np.linalg.eig(G)   # B の固有値と固有ベクトルを計算

In [41]:
eigen[0]     # 固有値からなるベクトル

array([46.20937271,  7.79062729, 10.        , 10.        ])

In [42]:
eigen[1]                   # 固有ベクトル

array([[-0.15115432,  0.72704996,  0.42816028, -0.21881893],
       [-0.34923733,  0.28320876, -0.82548112, -0.08249496],
       [-0.54732033, -0.16063243,  0.3664814 ,  0.82144671],
       [-0.74540333, -0.60447363,  0.03083944, -0.52013282]])

In [43]:
# B に固有ベクトルを掛け算し，要素ごとに固有ベクトルで割る．
# この操作で(非ゼロの)固有値が並んだ行列が得られる．
np.dot(G,eigen[1])/eigen[1]

array([[46.20937271,  7.79062729, 10.        , 10.        ],
       [46.20937271,  7.79062729, 10.        , 10.        ],
       [46.20937271,  7.79062729, 10.        , 10.        ],
       [46.20937271,  7.79062729, 10.        , 10.        ]])