In [1]:
import numpy as np
import scipy as sp

# Probability

In [2]:
np.random.choice(np.arange(1,7),10)

array([5, 3, 3, 1, 4, 1, 5, 6, 2, 5])

In [3]:
np.random.choice(np.arange(1,7),5,replace=False)  # 非復元抽出

array([1, 3, 2, 6, 5])

In [4]:
np.random.choice(np.arange(1,7),5)                # 復元抽出

array([3, 4, 1, 2, 6])

In [7]:
p = np.array([1,1,1,3,3,3]); p = p/np.sum(p)
np.random.choice(np.arange(1,7),10, p=p)

array([1, 4, 5, 6, 2, 2, 4, 6, 5, 5])

# 期待値と分散

In [8]:
x = np.random.normal(1,2,100)     # 期待値1，標準偏差2の正規分布にしたがうデータを100個生成   
x.mean()                          # データの平均値を計算．np.mean(x) と同じ

1.101579521802569

In [9]:
x.std()                           # データの標準偏差を計算．np.std(x) と同じ

2.2281571918205363

In [10]:
np.mean(np.abs(x-np.mean(x)) <= np.std(x))    # |x-E[x]]| ≦ sd(x) となるデータの割合

0.64

In [11]:
np.mean(np.abs(x-np.mean(x)) <= 2*np.std(x))  # |x-E[x]]| ≦ 2*sd(x) となるデータの割合

0.97

# 分位点

In [12]:
from scipy.stats import norm    # sp.stats.normを使う
sp.stats.norm.ppf(0.7)               # N(0,1)の 0.7点

0.5244005127080407

In [13]:
sp.stats.norm.ppf(0.7,loc=1,scale=2) # N(1,2**2)の 0.7点

2.0488010254160813

In [14]:
alpha = 0.05
sp.stats.norm.ppf(1-alpha) # N(0,1)の上側0.05点

1.6448536269514722

# 共分散，相関係数

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.data.shape            # データ数150, 次元4 

(150, 4)

In [16]:
np.cov(iris.data.T)        # 分散共分散行列(データ行列の転置を入れる)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [17]:
np.corrcoef(iris.data.T)   # 相関係数行列(データ行列の転置を入れる)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])