In [1]:
import numpy as np

In [2]:
np.random.choice(np.arange(1, 7), 10)

array([5, 6, 1, 6, 1, 5, 3, 5, 1, 2])

In [3]:
np.random.choice(np.arange(1, 7), 10, replace=True) # By default "replace" is "True"

array([5, 4, 6, 2, 6, 4, 6, 1, 5, 4])

In [4]:
np.random.choice(np.arange(1, 7), 5, replace=False)

array([3, 6, 4, 5, 2])

In [5]:
p = np.array([1, 1, 1, 3, 3, 3]); p = p / np.sum(p)
np.random.choice(np.arange(1, 7), 10, p = p)

array([6, 4, 2, 5, 6, 5, 1, 6, 1, 4])