In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import scipy as sp

In [3]:
%precision 3

'%.3f'

In [4]:
fish_data = np.array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [5]:
sp.sum(fish_data)

40

In [6]:
np.sum(fish_data)

40

In [7]:
sum(fish_data)

40

In [8]:
len(fish_data)

10

In [9]:
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.000

In [10]:
sp.mean(fish_data)

4.000

In [11]:
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.200

In [12]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [13]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [14]:
(fish_data - mu) ** 2

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [15]:
sp.sum((fish_data - mu) ** 2)

12.000

In [16]:
sp.var(fish_data, ddof = 0)

1.200

In [17]:
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.333

In [18]:
sp.var(fish_data, ddof = 1)

1.333

In [19]:
sigma = sp.sqrt(sigma_2)
sigma

1.155

In [20]:
sp.std(fish_data, ddof = 1)

1.155

In [21]:
sp.std(fish_data, ddof = 0)

1.095

In [22]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [23]:
sp.mean(fish_data - mu)

0.000

In [24]:
fish_data / sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [25]:
sp.std(fish_data / sigma, ddof = 1)

1.000

In [26]:
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [27]:
sp.mean(standard)

0.000

In [28]:
sp.std(standard, ddof = 1)

1.000

In [29]:
sp.amax(fish_data)

6

In [30]:
sp.amin(fish_data)

2

In [31]:
fish_data_2 = np.array([2, 3, 3, 4, 4, 4, 4, 5, 5, 100])

In [32]:
sp.mean(fish_data_2)

13.400

In [33]:
sp.median(fish_data_2)

4.000

In [34]:
from scipy import stats

In [35]:
fish_data_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
stats.scoreatpercentile(fish_data_3, 25)

3.000

In [36]:
stats.scoreatpercentile(fish_data_3, 75)

7.000